### ISSUE TITLE
Level Leaderboard

### ISSUE THREAD

**Issue by Volverine** [discordsuperutils/discord-super-utils#7]
Hello. Im new here :)
I just got working leveling bot from this repo but i would like to add a leaderboard of top 10 members, could you tell me how to do it?

**Comment by adam757521** [comment]
Hey! Thanks for using our library!
Making a leaderboard with discordSuperUtils is a VERY easy task.
simply,
```py
@bot.command()
async def leaderboard(ctx):
    guild_leaderboard = LevelingManager.get_leaderboard(ctx.guild)[:10]
    formatted_leaderboard = [f"Member: {x.member}, XP: {x.xp}" for x in guild_leaderboard]

    await discordSuperUtils.PageManager(ctx, discordSuperUtils.generate_embeds(
        formatted_leaderboard,
        title="Leveling Leaderboard",
        fields=25,
        description=f"Leaderboard of {ctx.guild}"
    )).run()
 ```
 If you have any other question, feel free to ask them in our [discord server](https://discord.com/invite/zhwcpTBBeC).

**Comment by Volverine** [comment]
Its working only with one person but if there is more people on the leaderboard it gets error:
Smth with other.net i guess
self.net is working fine.

```Ignoring exception in command leaderboard:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "bot4.py", line 29, in leaderboard
    guild_leaderboard = LevelingManager.get_leaderboard(ctx.guild)[:10]
  File "/serv/bot4/discordSuperUtils/Leveling.py", line 122, in get_leaderboard
    members.sort()
  File "/serv/bot4/discordSuperUtils/Leveling.py", line 26, in __lt__
    return self.net < other.net
AttributeError: 'LevelingAccount' object has no attribute 'net'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'LevelingAccount' object has no attribute 'net'```

**Comment by adam757521** [comment]
That issue will be fixed in the next release, it will be released later today

**Comment by adam757521** [comment]
0.1.3 has been released, that issue has been fixed.

**Comment by Volverine** [comment]
![image](https://user-images.githubusercontent.com/65069573/129479678-f1458a36-e073-44ae-bc79-19927509961a.png)

The order is wrong, any way to fix this without downloading whole release? Last time i couldnt import my database and we had to start collecting our levels from the beginning :P

**Comment by adam757521** [comment]
Yes, the reversed function to reverse the order.
We should make it reversed by default, sorry.
